### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by vr8hub** [dajare/anthony-trollope_harry-heathcote-of-gangoil#1]
We have to stop meeting like this…

Before I begin, an overall comment. We do not generally make wholesale changes to a transcription to match the scans, for a variety of reasons, not least because we don't know what edition PG (or whatever transcriber) used. Thus, all the changes to change the transcription's spelling from US to British, and to match the pagagraph breaks, etc., were unnecessary. (This has come up for me a couple of times lately, so I asked Alex about it [on the list](https://groups.google.com/g/standardebooks/c/-eHMW5Nyysw) today to make sure.) They're not _bad_, i.e. you don't have to undo them, but they're not necessary. And, like the dash changes from last time, trying to do so is a huge rabbit hole that is always longer and deeper than we expect. :) Which brings us to…

- [x] There are still some spelling changes to be made, e.g. I saw "favorable" more than once. There may be others; you might want to look through [this](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences) Wiki entry; it has a pretty good list of the differences.
- [x] There are also paragraph break differences remaining, e.g. "From all this…" begins a new one in chapter 1. As above, there may be others.
- [x] Rather than label commits as "Lint cleanup" or some such, it's better to identify what is actually being fixed in the commit message. This usually means multiple commits rather than one, but it provides much better context for someone looking at the commit history (including you). I too have been guilty of this (more than once) in the past, so it's something I had to learn (and have to remember) as well. :)
- [x] Do you think "A tale of Australian bush life" is a subtitle? It would appear so (to me) from the title page of the scans. If so, then it needs to be added to the metadata. There's no halftitlepage, so it won't actually appear anywhere reader-facing. See [SEMoS 9.4.2](https://standardebooks.org/manual/1.7.0/single-page#9.4.2) for details.
- [x] You fixed the doubles (yea!), but there's an instance of a semi-colon inside a single-quote ('new chum;') in chapter 7.
- [x] That's pretty much it, a nice clean production! Good job on the long description; I think I need to hire you to write mine…

**Comment by dajare** [comment]
> We have to stop meeting like this…

Call it "providence". :wink: 

- \#\# 3 (commit messages) and 6 (summary): noted! (And thanks for the encouraging word.)
- \# 1 (\~[or|our]\~) Ah, I see what I did wrong here: I was using regex to find matches at word boundaries, foolishly forgetting that some of those occur (like ~able, and others) *not* at word boundaries. I believe these are now complete and consistent. (N.b. `laborious`, `vigorously` are correct as they stand.)
- \#2 (paragraphing) I have gone through the whole, and caught a few more. **I (now) understand this to have been strictly speaking unnecessary, for SE.** But having started, we saw it through. If it hadn't been only ~40K words, it might have been different, too!
- \#4 (subtitle) Yes, I agree (having checked "worldcat", etc., just to be sure). I copy/pasted the model [in the manual](https://standardebooks.org/manual/1.7.0/single-page#9.4.2), so hopefully I've done that correctly.

I ran `se clean` again, and it completed silently.

Thanks for scrutinizing my work (again!). Hopefully I'll do better next time.

I've got one queued up, and have taken care in matching (as best as I can) PG transcript and page scans. But I know better now [how to proceed](https://groups.google.com/g/standardebooks/c/-eHMW5Nyysw). I think this transcript must have been a bit squiffy, as oddities and inconsistencies were what led me to do the checking in the first place. Hopefully the next one will be better!

**Comment by vr8hub** [comment]
- [ ] The punctuation changes (moving semi-colon outside quotes) are changing content (from the scans), and therefore should be [Editorial] commits. The latest one, and one of the former ones, are not so labeled (sorry, I missed the first message last time). You can just rebase and add [Editorial] to the front of the messages.
- [ ] While looking to see if there any other missing Britishisms, I ran across a substitution made in the transcription: "settled practice" in chapter 6 vs the scans' "settled purpose".
- [ ] Re Britishisms, in the "double l (el)" vs "single l" from the Wiki link, I found quarreled and traveled (quarrelled and travelled in the scans). Now that we're committed, I would suggest going through that entire Wiki entry and looking for matches for the American versions. Yep, tedious, I know, this is why we don't jump in that particular rabbit hole. :) But, it's a simple search, and you're probably not going to find most of the words, so you should be able to do all of it in a half-hour or less. Sorry! I can tell you that the "practice" and "recognize" that occur are correct; odd that it uses the US version of the latter.

The subtitle changes to the metadata look good.

**Comment by dajare** [comment]
@vr8hub - I can see why "rebase" brings so much angst. I followed [the tutorial](https://www.sitepoint.com/git-interactive-rebase-guide/) that [Alex recommended](https://groups.google.com/g/standardebooks/c/WquRIXGzkq4/m/ElnUiSZrAAAJ) ... and I don't think it went well. Instead of *replacing* the commit messages (and squashing two identical commits), it did that AND **added** the whole on to "HEAD". So instead of 40(ish) commits with changes, there are now 49 commits, and the original trail is still there. :disappointed: 

I'm a little uncertain how now to proceed. I wanted to clean up the repo before proceeding with the rest of the Britishisms (sigh). 

Here's an annotated image to explain what's there (and why I attempted what I did):

![Screenshot from 2022-09-29 11-15-03](https://user-images.githubusercontent.com/40625/193009701-8f687eee-bdc6-4deb-b7a5-6138a54e18a7.png)

So, I tried to `squash` 1b4d0ba and 89c88d3 (since they are, literally, the *same* commit, just one has the correct message), and `reword` 32ddef6. But it seems not to have gone well.

I **have kept a copy of the repo before rebase**!! But if I delete this public repo with that one, we'll lose this issue trail.

So ... I'm puzzled and, truth be told, a little downcast! I spend a good amount of time with that tutorial (and others!) before proceeding. **N.b.** I am also using "github Desktop" to manage sync'ing between machine and Github-online. This could be a factor.

I'd be grateful for your advice. This little 40K novel feels like it's getting out of hand.

**Comment by vr8hub** [comment]
In the words of Mr. Adams, Don't Panic. (And Always Carry a Towel.) You have a copy, and _I_ have a copy, so no matter what else happens, we can get back to where you were, and try however many times it takes to get to where we want to be.

The TL;DR version is I believe you're correct; once you do a rebase, you have to do a force push to the other end (either local to remote if the rebase was made locally, or remote to local if the changes were made remotely).
Although many/most on the list swear by git GUI's, this is one of the reasons I only use the git command line and I only use it on local repositories; there's never anything happening that I didn't directly cause with a command line. The only thing I use GitHub for is to push the repository when I'm ready for review (or after changes during one). Again, I'm the odd person out here, but that's _why_ I'm the odd person out. :) Consequently, I only know one way out of here, and it's through the command line. Many others on the list would probably be of more and varied help.

Just as information, I believe all of this started with changes being made in two places, once on the local repository, and once on the remote one. Here's part of the output from my `git hist` command (`hist` is just an alias for log --pretty=format blah blah).
````
*   80c8517 2022-09-26 18:32:56 | Merge branch 'master' of https://github.com/dajare/anthony-trollope_harry-heathcote-of-gangoil [David]
|\
| * 1b4d0ba 2022-09-26 18:23:17 | Typography fixes [David]
* | 89c88d3 2022-09-26 18:23:17 | [Editorial] Typography fixes [David]
|/
````
The asterisks show the changes being on different copies: the one on the right on 1b4d0ba (remote?) and on the left on 89c88d3 (local?). And then the merge that brought them both together, i.e. put them back in sync.

I just did a simple rebase to my local copy of the repository (that I used for the review), without making _any_ changes (including reword), and it did what I wanted, i.e. got rid of that branch/merge, and now there's only one commit. I believe the rebase "does the right thing" in this case, because instead of merging two identical commits (one local, one remote), the rebase ditches the identical remote one and leaves just the local one, which is all we need. (I can usually (often?) get git to do what I want, but I often don't know _why_ it did it.)

````
* e9b1c8d 2022-09-28 15:47:26 | Ch 7: fix punctuation [David]
* 89c88d3 2022-09-26 18:23:17 | [Editorial] Typography fixes [David]
* 6b7a5a2 2022-09-25 20:25:51 | [Lint] fixes [David]
````

At that point, all I had to do is do a second rebase and reword e9b1c8d, and voilà! Then I would have to do a force push to GitHub to get it back synced with my now correct local repository, but of course I won't do that, since this is your repository, not mine. :)

So, _**a**_ way out is to do that; get a local copy of the repository _before_ you tried the rebase. (You didn't say whether the copy you made was local or remote; if it was local, then just make a copy of that copy, if it was remote, then you'll have to clone a copy locally of the remote copy.) Once you have a local copy that is before the rebase, just do a `rebase --interactive 89c88d3` (where 89c88d3 is whatever id is on the "[Editorial] Typography fixes", because it's the next commit, i.e. the remote one, we want to affect). If then drops you in the editor so you can tell it what you want to do. I didn't do anything—I just did a `:wq` to get out (I use vim as my command-line editor, so if you don't, do whatever you do to just exit your editor).
I then did a `git rebase --continue` to "complete" the rebase. And when I was done, no more duplicate (remote) commit. If that's your result, then do a second rebase to reword the most recent changes (Final ~or|our~ fixes…). At that point, your local repository should be good to go. You can look at the log to confirm, confirm that there were no actual changes made (git status should show nothing, etc.).

Then all you have to do is force push those changes back up to the remote (GitHub) repository with a `git push -f origin master` (substituting whatever you named your remote for `origin` and whatever your repository is named for `master` (the latter might be main if you let GitHub name it). Note that the local repository should be pointing to your original (keep your "clean" copy in case of emergency). A `git remote -v` will show you where your local repository is pointed, and the same command (with different options; see `man git-remote`) will point it to where you want if you need to change it. Just make sure, if your "copy" was a remote copy, that your local is not pointed to that copy (you want to keep the copy so this can all be redone/retried if needed). You want it pointed to the original.

As I said, you can probably fix this via the GUI. I just don't know how, so it would take me a lot of reading and experimentation to figure out. You are of course free to try whatever you like; as long as you, and I, have a copy of the changes before the rebase, then no matter how big a mess happens, we can start over an infinite number of times (relatively speaking).

I hope this made some level of sense. If not, we have copies, we shall try again. Good luck!

**Comment by dajare** [comment]
@vr8hub - Yr a star. Thank you so much for this work of supererogation. It's getting late here, so I'll return to this tomorrow (when time is at a premium). But it's starting to make a dim sort of sense. My copy is *local*, and I understand what you say about "copy of copy". But we'll see how we go. Thanks for your support and guidance! Much appreciated.

Hopefully next news will be good news!

**Comment by vr8hub** [comment]
Excellent, glad to hear it. This wasn't too big a hurdle; we've had some doozies on other productions (and I've caused a few myself).

Everything looks good—I cloned this to a new directory, and it looks the same as the old one after I tried my rebase, so I think you're a go for the rest.

**Comment by dajare** [comment]
OK, I think (_think_) we're done. I went through the wiki page item-by-item, checking any discrepancies against the scans. There were several cases of single- to double-"ell" (and on of the converse), and a handful of other tweaks. It is within the realm of the possible that I might have missed something, but I've done my best.

That "settled [practice|purpose]" difference (sharp eyes!) is like some of the other oddities I found in this transcription (especially in the punctuation of "Jacko's" dialog), where the nuance of meaning is affected. Odd, I think, as this one isn't even UK/US! Just ... odd. (And it makes me wonder whether the proof-reading on this transcript was squiffy. Dunno.)

Anyway! I hope we're there, but you can see whether this is ready for Alex now. I continue to live in hope. :grimacing:

**Comment by vr8hub** [comment]
Since PGDP is involved, I can only assume that they found or had a physical copy of a US edition, and transcribed from that. I searched the "big three" places (Google, Hathi, IA) and found only dozens of copies of the edition you used. If it had been just a person or two doing the transcription, I could (barely) envision them making changes themselves, but since it was PGDP, that would suggest that scans were involved, and therefore the changes you note were done by the (theoretical) US publisher.

My apologies, I keep finding things I should have noticed the first round. (I'm adding to my list of things to check for reviews!) PGDP _was_ involved, according to the "E-text prepared by…" line in the PG text, but they are not listed as transcribers in the metadata. They need to be added, and note they have a URL (you can see _Tom Jones_ for an example of what their entry looks like). Normally `create-draft` handles this, but there are occasionally issues with the PG text that prevent it from doing so.

After that, I think it's ready for Alex!

**Comment by dajare** [comment]
OK, PGDP added to meta! (Odd that the `colophon.xhtml` should be correct, but missed in `content.opf`. Hey ho...)

Yeah, oddness in this one. Hopefully my next attempt will not have this sort of complication. I'll do my best to ensure it doesn't!

Meanwhile, again, if you're happy with my tweak, over to Alex!
